# An example scene file (3)

[camera]
center = [-5.0, 10.0, 5.0]
target = [0.0, 0.0, 0.0]
roll = 0.0

[light]
center = [-3.0, 3.0, 11.0]

[[planes]]
center = [0.0, 0.0, -10.0]
normal = [0.0, 0.0, 1.0]
scale = 0.15
texture = "../textures/01tizeta_floor_f.png"

[[planes]]
center = [0.0, -16.0, 0.0]
normal = [0.0, 1.0, 0.0]
scale = 0.15
reflect = 0.65
texture = "../textures/trak2_tile1b.png"

[[planes]]
center = [16.0, 0.0, 0.0]
normal = [-1.0, 0.0, 0.0]
scale = 0.15
texture = "../textures/02camino.png"

[[spheres]]
center = [0.64, 1.36, -1.74]
radius = 0.54
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [0.64, 1.36, 1.18]
radius = 0.59
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [3.45, 1.36, 2.30]
radius = 0.59
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [4.32, 3.28, 3.52]
radius = 0.52
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [4.96, -0.54, 2.03]
radius = 0.52
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [-0.88, -1.21, 1.88]
radius = 0.59
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [-2.72, -1.63, -0.48]
radius = 0.59
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [-1.00, -0.83, -2.85]
radius = 0.59
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [-0.28, 3.15, 2.06]
radius = 0.35
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [0.50, -2.91, 2.14]
radius = 0.35
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [-2.00, -0.99, 3.76]
radius = 0.35
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [-3.39, -3.72, -0.63]
radius = 0.35
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [-4.53, -0.39, -0.33]
radius = 0.35
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [0.24, -2.50, -3.56]
radius = 0.35
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [-2.22, -0.16, -4.55]
radius = 0.35
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [-0.31, 3.05, -2.36]
radius = 0.35
texture = "../textures/trak_light2b.png"

[[spheres]]
center = [2.58, 1.33, -2.36]
radius = 0.35
texture = "../textures/trak_light2b.png"

[[cylinders]]
center = [0.64, 1.36, -0.28]
direction = [0.00, 0.00, 2.92]
radius = 0.20
span = 1.46
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [2.05, 1.36, 1.74]
direction = [2.81, 0.00, 1.11]
radius = 0.20
span = 1.51
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [3.88, 2.32, 2.91]
direction = [0.87, 1.93, 1.22]
radius = 0.20
span = 1.22
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [4.21, 0.41, 2.16]
direction = [1.51, -1.89, -0.26]
radius = 0.20
span = 1.22
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [-0.12, 0.07, 1.53]
direction = [-1.52, -2.56, 0.69]
radius = 0.20
span = 1.53
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [-1.80, -1.42, 0.70]
direction = [-1.85, -0.42, -2.36]
radius = 0.20
span = 1.51
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [-0.18, 0.26, -2.29]
direction = [-1.64, -2.19, -1.11]
radius = 0.20
span = 1.48
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [-1.86, -1.23, -1.66]
direction = [1.72, 0.80, -2.37]
radius = 0.20
span = 1.52
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [0.18, 2.25, 1.62]
direction = [-0.92, 1.80, 0.87]
radius = 0.20
span = 1.10
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [-0.19, -2.06, 2.01]
direction = [1.37, -1.70, 0.27]
radius = 0.20
span = 1.10
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [-1.44, -1.10, 2.82]
direction = [-1.13, 0.22, 1.88]
radius = 0.20
span = 1.10
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [-3.06, -2.68, -0.55]
direction = [-0.67, -2.09, -0.15]
radius = 0.20
span = 1.10
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [-3.63, -1.01, -0.40]
direction = [-1.81, 1.24, 0.15]
radius = 0.20
span = 1.10
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [-0.38, -1.67, -3.21]
direction = [1.24, -1.67, -0.71]
radius = 0.20
span = 1.10
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [-1.61, -0.49, -3.70]
direction = [-1.22, 0.67, -1.70]
radius = 0.20
span = 1.10
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [0.17, 2.20, -2.05]
direction = [-0.95, 1.69, -0.63]
radius = 0.20
span = 1.02
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [1.61, 1.35, -2.05]
direction = [1.94, -0.02, -0.63]
radius = 0.20
span = 1.02
texture = "../textures/qubodup-light_wood.png"

