# An example scene file (2)

[camera]
center = [10.0, -10.0, 3.0]
target = [0.0, 0.0, 5.0]
roll = 0.0

[light]
center = [5.0, 5.0, 5.0]

[[planes]]
center = [0.0, 0.0, 0.0]
normal = [0.0, 0.0, 1.0]
scale = 0.15
reflect = 0.75
texture = "../textures/trak2_tile1b.png"

[[planes]]
center = [0.0, 0.0, 17.0]
normal = [0.0, 0.0, -1.0]
scale = 0.15
texture = "../textures/04univ3.png"

[[planes]]
center = [-17.0, 0.0, 0.0]
normal = [1.0, 0.0, 0.0]
scale = 0.25
texture = "../textures/trak_light2b.png"

[[planes]]
center = [0.0, -17.0, 0.0]
normal = [0.0, 1.0, 0.0]
scale = 0.15
texture = "../textures/01tizeta_floor_g.png"

[[planes]]
center = [17.0, 0.0, 0.0]
normal = [-1.0, 0.0, 0.0]
scale = 0.15
texture = "../textures/01tizeta_floor_f.png"

[[planes]]
center = [0.0, 17.0, 0.0]
normal = [0.0, -1.0, 0.0]
scale = 0.15
texture = "../textures/04univ2.png"

[[cylinders]]
center = [5.0, 0.0, 0.0]
direction = [0.0, 0.0, 1.0]
radius = 0.7
span = -1.0
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [0.0, 0.0, 0.0]
direction = [0.0, 0.0, 1.0]
radius = 0.7
span = -1.0
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [-5.0, 0.0, 0.0]
direction = [0.0, 0.0, 1.0]
radius = 0.7
span = -1.0
texture = "../textures/qubodup-light_wood.png"

[[cylinders]]
center = [0.0, 0.0, 15.0]
direction = [1.0, 0.0, 0.0]
radius = 0.7
span = -1.0
texture = "../textures/qubodup-light_wood.png"

