# An example scene file

[camera]
center = [12.0, 4.0, 7.0]
target = [0.0, 0.0, 1.0]
roll = 0.0

[light]
center = [5.0, -5.0, 5.0]

[[planes]]
center = [0.0, 0.0, 0.0]
normal = [0.0, 0.0, 1.0]
scale = 0.15
texture = "../textures/04univ2.png"

[[planes]]
center = [-12.0, 0.0, 0.0]
normal = [1.0, 0.0, 0.0]
scale = 0.15
texture = "../textures/01tizeta_floor_g.png"

[[planes]]
center = [0.0, -12.0, 0.0]
normal = [0.0, 1.0, 0.0]
scale = 0.25
texture = "../textures/trak_light2b.png"

[[cylinders]]
center = [0.0, 0.0, 0.0]
direction = [0.0, 0.0, 1.0]
radius = 1.0
span = -1.0
texture = "../textures/qubodup-light_wood.png"

[[spheres]]
center = [3.0, 5.0, 1.2]
radius = 1.2
axis = [0.0, 1.0, 0.5]
texture = "../textures/02camino.png"

[[spheres]]
center = [-3.0, 5.0, 1.2]
radius = 1.2
axis = [0.0, 1.0, 0.5]
texture = "../textures/02camino.png"

[[spheres]]
center = [-1.0, -5.0, 1.2]
radius = 1.2
axis = [0.0, 1.0, 0.5]
texture = "../textures/02camino.png"

